# Generated by Django 5.2.17 on 2026-09-03 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='año_publicacion',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2100)], verbose_name='Año de Publicacion'),
        ),
    ]
