# Generated by Django 5.2.17 on 2026-09-03 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_alter_libro_año_publicacion'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='libro',
            table='libro',
        ),
    ]
